/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.tools.semantic.release

import java.io.File

fun main(args: Array<String>) {
    println("Processing...")
    val repository = VersionedRepository(File("/mnt/c/Workspace/test-data-gen"))
    println("Current version: ${repository.currentVersion}")
    println("Unprocessed messages:")
    repository.untaggedMessages.forEach {
        println("\t$it")
    }


}

fun autoBump(repository: VersionedRepository) {
    val currentVersion = repository.currentVersion
}